name=Smart_ASHA_Inference
version=1.0.0
author=Edge Impulse
maintainer=Edge Impulse
sentence=Edge Impulse inference library for Smart Asha
paragraph=Edge Impulse inference library
category=Machine Learning
url=https://edgeimpulse.com
architectures=*
includes=Smart_ASHA_Inference.h
