/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_951794_3_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_951794_1[] = { "Hazard", "Normal", "Respiratory", "Stress" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_951794_2_axes[] = { 0, 1, 2, 3, 4, 5, 6 };
const uint32_t ei_dsp_config_951794_2_axes_size = 7;
ei_dsp_config_spectral_analysis_t ei_dsp_config_951794_2 = {
    2, // uint32_t blockId
    4, // int implementationVersion
    7, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    5.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    64, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_951794_2[77] = { 664.4234268775353, -0.7310535586665747, 3.0887068397197606, 2.8809569492936133, 8.204393696011259, 6.721784601761745, 6.663569850188035, 6.630482557186713, 6.511557121918751, 6.362794297933578, 6.068111651218855, 4302.973954811348, -3.801426019293901, 20.739884841460018, 1.8529120629796616, 3.372327513534289, 4.841379739114871, 4.7866563307551235, 4.726069264113903, 4.658094737736079, 4.533317745534274, 4.249509448271532, 45.84275369093968, -2.1597514635305672, 11.535677911638441, 2.5027393995569303, 5.765603116383919, 4.321912567202862, 4.258334416838792, 4.211348093472994, 4.082815996958659, 3.9291661051603466, 3.625830591412691, 13279.614528909196, -5.117069796200555, 29.083831509002128, 1.7615034154974498, 1.8435877294494556, 7.930877050528159, 7.898009955883026, 7.850708491985614, 7.76940854535653, 7.6273695551432095, 7.291701171489862, 5.1057832406117365, -5.766460298574888, 33.031108494905325, 1.8849633769347118, 1.9959249050571368, 2.8221402544241685, 2.793993639258238, 2.741737751548107, 2.6559689886294877, 2.4996305105777887, 2.1328104330943183, 1.0486691645704782, 5.7474659456656525, 32.877202554849475, 1.8890589088201524, 2.017064756498887, 1.4436579760450583, 1.414863734262494, 1.363180298759387, 1.2761767197686893, 1.1201126511853474, 0.7546036374110442, 0.7501708306945287, 5.679727310916552, 32.415044303123764, 1.9068836568639829, 2.1220773950219156, 1.1455569792825442, 1.11420973315835, 1.0638729912443803, 0.9756124834315135, 0.8231676738709212, 0.45533513789190555 };
const float ei_dn_standard_scaler_scale_951794_2[77] = { 0.003132550941830356, 0.8845344294611082, 0.1994944170231682, 1.3881949526602964, 0.19819196153801036, 2.0130389149889174, 2.073234420247518, 2.265288647769853, 2.2720135857225388, 2.1327027699985783, 1.9293700246426642, 0.0002612975716396111, 0.39941604390350904, 0.06764616450954936, 0.8023814144326309, 0.15250711352880966, 0.13135494392502634, 0.13187909057303662, 0.13243613195495377, 0.13305075665505695, 0.13419422597130934, 0.13686426653974357, 0.011289881601573709, 0.545613701447298, 0.14898404913235228, 1.5936292857353838, 0.24153490660719254, 1.7897943902872786, 2.0589282069296932, 2.204186319663443, 2.4390950938577904, 2.488227057970084, 2.283392989617966, 0.0002002901194932581, 0.557015332169946, 0.09375597978638861, 1.578572352431959, 0.38052617406468586, 0.17645950971834334, 0.17679893821475945, 0.17725771581889177, 0.17804996189925454, 0.17945409053433944, 0.182873247279689, 127.7894216785964, 61.907444226140335, 8.202978421766824, 57.149202134590816, 10.82142576929966, 171.05686177264855, 151.76304890286272, 137.9327633909902, 117.13625113006444, 103.07300244749476, 75.22379479419307, 11.27027333049938, 5.183625277270287, 0.6466231624515086, 19.825194785583477, 3.4502996584506187, 14.542302699759706, 13.207094283343896, 14.563707179006649, 13.552292505635076, 14.275951837746595, 13.985857224247608, 9.523866444401941, 2.198732212424516, 0.34414512891232313, 7.127763818965112, 1.140843852445995, 7.808321935203642, 7.918749787822223, 8.201345027694755, 7.712535904388915, 8.09393015499397, 7.603045444438679 };
const float ei_dn_standard_scaler_var_951794_2[77] = { 101906.92930613842, 1.2781167195093281, 25.126876641279686, 0.518918409108829, 25.458213721340677, 0.24677187388929264, 0.23265006545697378, 0.19487355273800244, 0.1937216467242961, 0.21985651215663093, 0.2686389282875356, 14646344.758010935, 6.268288667434328, 218.53129790642342, 1.553238972255004, 42.99518255720751, 57.95716762313526, 57.49738757765693, 57.0147237279989, 56.48918416694271, 55.530596761075394, 53.385074274128684, 7845.510809433478, 3.3591505190187667, 45.05266159145199, 0.39375437824778753, 17.141159352236954, 0.31217183331078496, 0.2358943794086715, 0.20582749796039163, 0.16809025449621753, 0.16151764845839006, 0.19179561479695556, 24927627.639474172, 3.2230400407355493, 113.76326467447652, 0.40130171491534483, 6.90606928073252, 32.11514325034237, 31.991948723071317, 31.826560200470606, 31.543961198363483, 31.052264411074557, 29.9019593360077, 0.00006123647605021579, 0.00026092413348762254, 0.014861302071178797, 0.00030618200094571703, 0.008539472230632762, 0.00003417582441089874, 0.00004341781004066719, 0.000052561182326560405, 0.00007288150946035957, 0.0000941261176693277, 0.0001767215545720883, 0.007872834144472025, 0.03721626642008547, 2.391649235912627, 0.0025442809953788673, 0.08400137009756183, 0.004728611557893822, 0.005733046226511603, 0.004714722362058323, 0.005444706409986126, 0.004906703910413434, 0.005112364602890423, 0.01102486821577985, 0.2068499031357025, 8.44338798774731, 0.01968309544783183, 0.7683296393311756, 0.01640153814152771, 0.015947285113067422, 0.014867222265948402, 0.016811466609050217, 0.015264447698279199, 0.017299152505480718 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_951794_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_951794_2,
    .mean_data_len = 77,
    .scale_data = (float *)ei_dn_standard_scaler_scale_951794_2,
    .scale_data_len = 77,
    .var_data = (float *)ei_dn_standard_scaler_var_951794_2,
    .var_data_len = 77
};
ei_data_normalization_t ei_data_normalization_config_951794_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_951794_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_951794_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_951794_1[ei_dsp_blocks_951794_1_size] = {
    { // DSP block 2
        2,
        77, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_951794_2, // pointer to config struct
        ei_dsp_config_951794_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_951794_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_951794_2, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_951794_3 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_951794_3_init,
    .model_invoke = &tflite_learn_951794_3_invoke,
    .model_reset = &tflite_learn_951794_3_reset,
    .model_input = &tflite_learn_951794_3_input,
    .model_output = &tflite_learn_951794_3_output,
};

const uint8_t ei_output_tensors_indices_951794_3[1] = { 0 };
const uint8_t ei_output_tensors_size_951794_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_951794_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_951794_3,
    .output_tensors_size = ei_output_tensors_size_951794_3,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_951794_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_951794_1_size = 1;
const uint32_t ei_learning_block_951794_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_951794_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_951794_1[ei_learning_blocks_951794_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_951794_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_951794_3_inputs,
        ei_learning_block_951794_3_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_951794_3 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_951794_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_951794_1[ei_postprocessing_blocks_951794_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_951794_3,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_951794_1_size = 0;

uint32_t *freeform_outputs_951794_1 = nullptr;

const ei_impulse_t impulse_951794_1 = {
    .project_id = 951794,
    .project_owner = "vansh1409",
    .project_name = "AROGYA AI",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 77,
    .raw_sample_count = 250,
    .raw_samples_per_frame = 7,
    .dsp_input_frame_size = 250 * 7,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_951794_1_size,
    .dsp_blocks = ei_dsp_blocks_951794_1,

    .learning_blocks_size = ei_learning_blocks_951794_1_size,
    .learning_blocks = ei_learning_blocks_951794_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_951794_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_951794_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "ecg + gsr + gas + pulse + temp + acc_x + acc_y",
    .slice_size = (250/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 4,
    .categories = ei_classifier_inferencing_categories_951794_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_951794_1_size,
    .freeform_outputs = freeform_outputs_951794_1
};

ei_impulse_handle_t impulse_handle_951794_1 = ei_impulse_handle_t( &impulse_951794_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_951794_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_951794_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_951794_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_951794_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
